import streamlit as st
import psycopg2

# Configuração da Página de Setup
st.set_page_config(page_title="Instalador Estamparia", page_icon="🏗️")
st.title("🏗️ Criador de Tabelas - Estamparia (V2)")
st.warning("Este script cria as tabelas com o prefixo 'estamparia_' no Supabase.")

# Função de Conexão (Padrão Blindado)
def init_connection():
    try:
        return psycopg2.connect(
            host=st.secrets["postgres"]["DB_HOST"],
            user=st.secrets["postgres"]["DB_USER"],
            password=st.secrets["postgres"]["DB_PASS"],
            dbname=st.secrets["postgres"]["DB_NAME"],
            port=st.secrets["postgres"]["DB_PORT"],
            sslmode='require'
        )
    except Exception as e:
        st.error(f"Erro de Conexão: {e}")
        return None

# SQL de Criação das Tabelas
SQL_SCRIPT = """
-- 1. Tabela de Apontamentos
CREATE TABLE IF NOT EXISTS estamparia_apontamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data TEXT, 
    cliente TEXT, 
    descricao_pc TEXT, 
    operacao TEXT, 
    materia_prima TEXT, 
    maquina TEXT, 
    tempo_ciclo_seg REAL, 
    operador TEXT, 
    setup_min INTEGER, 
    inicio_prod TEXT, 
    fim_prod TEXT, 
    qtd_produzida INTEGER, 
    refugo INTEGER,
    meta_pc_hora INTEGER DEFAULT 0, 
    custo_refugo_unit REAL DEFAULT 0, 
    ativo INTEGER DEFAULT 1
);

-- 2. Tabela de Paradas (Registro)
CREATE TABLE IF NOT EXISTS estamparia_paradas_reg (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data TEXT, 
    maquina TEXT, 
    motivo TEXT, 
    inicio TEXT, 
    fim TEXT, 
    observacao TEXT, 
    ativo INTEGER DEFAULT 1
);

-- 3. Cadastros Básicos
CREATE TABLE IF NOT EXISTS estamparia_operadores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT UNIQUE, 
    ativo INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS estamparia_maquinas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT UNIQUE, 
    horimetro_total REAL DEFAULT 0, 
    meta_manutencao REAL DEFAULT 500, 
    ativo INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS estamparia_manutencoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_manut TEXT, 
    maquina TEXT, 
    tipo_manut TEXT, 
    descricao TEXT, 
    tecnico TEXT, 
    ativo INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS estamparia_cad_operacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT UNIQUE, 
    ativo INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS estamparia_cad_materias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT UNIQUE, 
    ativo INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS estamparia_cad_paradas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT UNIQUE, 
    ativo INTEGER DEFAULT 1
);

-- 4. Inserir Dados Iniciais (Seus padrões IPAR)
-- Operações
INSERT INTO estamparia_cad_operacoes (nome) VALUES 
('CORTE'), ('DOBRA'), ('REPUXO'), ('FURACAO'),
('AR (ARRUELA)'), ('ARRPX (ARRUELA RPX)'), ('DS (DISCO)'), 
('F (FUROS)'), ('ML (MIOLO)'), ('MM (MAMICA)')
ON CONFLICT (nome) DO NOTHING;

-- Matérias
INSERT INTO estamparia_cad_materias (nome) VALUES 
('ACO CARBONO'), ('INOX'), ('ALUMINIO'),
('BC (BICO)'), ('CH (CHAPA)'), ('DS (DISCÃO)'), 
('DS SUPER (DISCO SUPER)'), ('DSQ (DISQUINHO)'), ('RT (RETALHO)'), ('SB (SOBRA)')
ON CONFLICT (nome) DO NOTHING;

-- Motivos de Parada
INSERT INTO estamparia_cad_paradas (nome) VALUES 
('Ausência Operador'), ('Inspeção de Qualidade'), ('Limpeza / 5S'),
('P1 - AFIAÇÃO DE FERRAMENTA'), ('P2 - FALTA DE FERRAMENTA'), 
('P3 - SELECIONAR MATÉRIA-PRIMA'), ('P4 - FALTA DE PRODUÇÃO'), 
('P5 - QUEBRA DE GARRA'), ('P6 - QUEBRA MECÂNICA'), 
('P7 - PANE ELÉTRICA'), ('P8 - FALTA DE ENERGIA'), 
('P9 - OUTROS'), ('Setup / Troca de Estampo')
ON CONFLICT (nome) DO NOTHING;
"""

if st.button("🚀 CRIAR TABELAS 'ESTAMPARIA_' AGORA"):
    conn = init_connection()
    if conn:
        cur = conn.cursor()
        try:
            # Executa o script inteiro
            cur.execute(SQL_SCRIPT)
            conn.commit()
            st.success("✅ SUCESSO! Tabelas com prefixo 'estamparia_' criadas.")
            st.info("Dados padrão (AR, BC, P1...) inseridos.")
        except Exception as e:
            st.error(f"Erro ao criar tabelas: {e}")
        finally:
            cur.close()
            conn.close()